name: Sitemap Crawler

on:
  schedule:
    - cron: '0 2 * * *'  # Täglich um 2 Uhr morgens
  workflow_dispatch:     # Manuelle Auslösung ermöglichen

jobs:
  crawl-sitemap:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install puppeteer axios xml2js
        
      - name: Crawl Sitemap
        run: node ./scripts/crawl-sitemap.js
        env:
          SITEMAP_URL: ${{ secrets.SITEMAP_URL }}
          USER_AGENT: "SitemapCrawler/1.0 (GitHub Actions)"
          
      - name: Log results
        run: |
          echo "Sitemap crawling completed at $(date)"
          echo "URLs crawled: $(cat ./crawl-results.json | jq length)"
